version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_enzyme_replace_1:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-08-01 to 2021-10-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/inp*.feather
  
  generate_enzyme_replace_2:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-11-01 to 2021-12-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/in*.feather

  generate_measures_enzymeRx:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: 
      [
        generate_enzyme_replace_1,
        generate_enzyme_replace_2,
      ]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_enzymeRx*_rate.csv

  describe_ERx_rates:
    run: r:latest analysis/analysis_enzymeRx.R
    needs: 
      [
        generate_measures_enzymeRx,
      ]
    outputs:
      moderately_sensitive:
        Fig1: output/ERx_number.png
        Fig2: output/ERx_rates.png
