version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_enzyme_replace_1:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2015-01-01 to 2018-08-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/inp*.feather
  
  generate_enzyme_replace_2:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2018-09-01 to 2023-09-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/in*.feather

  generate_measures_enzymeRx:
    run: cohortextractor:latest generate_measures --study-definition study_definition --skip-existing --output-dir=output/measures
    needs: 
      [
        generate_enzyme_replace_1,
        generate_enzyme_replace_2,
      ]
    outputs:
      moderately_sensitive:
        measure_csv1: output/measures/measure_enzymeRx*_rate.csv
        measure_csv2: output/measures/measure_ExByRegion*_rate.csv

  describe_ERx_rates:
    run: r:latest analysis/analysis_enzymeRx.R
    needs: [generate_measures_enzymeRx]
    outputs:
      moderately_sensitive:
        Fig1: output/ERx_number.png
        Fig2: output/ERx_rates.png
        Fig3: output/model_rates.png
        Fig4: output/Region.png
        Fig5: output/Figure_3A_East.png
        Fig6: output/Figure_3B_East Midlands.png
        Fig7: output/Figure_3C_London.png
        Fig8: output/Figure_3D_North East.png
        Fig9: output/Figure_3E_North West.png
        Fig10: output/Figure_3F_South East.png
        Fig11: output/Figure_3G_South West.png
        Fig12: output/Figure_3H_West Midlands.png
        Fig13: output/Figure_3I_Yorkshire and The Humber.png
        csv3: output/ERx_Rates_rounded.csv
        csv4: output/Region_rounded.csv
  
  generate_report:
    run: r:latest analysis/Produce_html.R
    needs: [describe_ERx_rates]
    outputs:
      moderately_sensitive:
        cohort: output/Report_file.html

  # generate_notebook:
  #   run: jupyter:latest jupyter nbconvert /workspace/analysis/reportEx.ipynb --execute --to html --template basic --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400 --no-input
  #   needs: [describe_ERx_rates]
  #   outputs:
  #     moderately_sensitive:
  #       notebook: output/reportEx.html